### PR TITLE
Upgrade to ol6

### PR DESCRIPTION
**Pull request by pjjmunier**
## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [x] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [x] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [x] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [x] Autres (décrire ci-après) :  maj dépendance

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [x] Non

### CODE REVIEW

**Review by elias75015 — APPROVED** [review]
Test manuel de tous les exemples : aucune anomalie repérée.
Test unitaires mocha passent aussi.

Je ne sais pas trop quoi regarder d'autre...pour moi c'est OK :+1: 

@lowzonenose tu peux jeter un coup d'oeil ?

**Comment by elias75015** [comment]
J'ai refait un tour un reprenant point par point le changelog d'openlayers 6.0.0 --> pas de soucis côté extensions repéré...

PR toujours en attente des review SDK + portail

**Review by lowzonenose — APPROVED** [review]

**Comment by lowzonenose** [comment]
# checklist

* https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md

**!!! Usage of map.forEachLayerAtPixel**

Removal of CSS print rules

The setCenter, setZoom, setResolution and setRotation methods on ol/View 
do not bypass constraints anymore

**!!! Removal of the constrainResolution option on View.fit, PinchZoom, 
MouseWheelZoom and ol/interaction.js**

The view extent option now applies to the whole viewport

The view is constrained so only one world is visible

**!!! Removal of deprecated methods : inherits**

**!!! New internal tile coordinates**
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#new-internal-tile-coordinates

Removal of the "vector" render mode for vector tile layers : hybrid

Removal of the "renderMode" option for vector layers
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#removal-of-the-rendermode-option-for-vector-layers

New declutter behavior

New prerender and postrender layer events replace old precompose, render 
and postcompose events

New getVectorContext function provides access to the immediate vector 
rendering API

Layers can only be added to a single map

**!!! The OverviewMap requires a list of layers.**

**!!! The ol/Graticule has been replaced by ol/layer/Graticule**

**!!! ol/format/Feature API change**

**!!! ol/VectorTile API changes**
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#olvectortile-api-changes

Drop of support for the experimental WebGL renderer

Removal of the AtlasManager

Change of the behavior of the vector source's clear() and refresh() methods

**!!! Renaming of getGetFeatureInfoUrl to getFeatureInfoUrl**

**!!! getFeaturesAtPixel always returns an array**

Hit detection with unfilled styles


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.1.0.md

A new, performance optimized hit detection API on the layer level, Layer#t 
(pixel) has been introduced. At this point it is implemented for vector, 
vector tile and image vector layers, and is recommended when performance 
is critical, e.g. for hit detection on mouseover.


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.2.0.md

Vector tile layers now have a vector render mode, which brings improved 
zooming experience for sources with not too much data.

Several improvements have been made to the KML parser for reading styles, 
bringing the rendered result much closer to Google Earth.


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.3.0.md

Better support for KML icon colors, as well as fills and outlines in PolyStyle

Several improvements to the Graticule layer, like consistent labeling, 
no more missing graticule lines, and it now works for views that cross 
the date line.

Most of the rendering code can now be run in web workers, e.g. to render 
to an OffscreenCanvas


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.4.0.md

Map interactions work again when ol.css is not included in the build.

Better cache management for tile layers.

**Comment by lowzonenose** [comment]
# checklist

* https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md

**!!! Usage of map.forEachLayerAtPixel**

Removal of CSS print rules

The setCenter, setZoom, setResolution and setRotation methods on ol/View 
do not bypass constraints anymore

**!!! Removal of the constrainResolution option on View.fit, PinchZoom, 
MouseWheelZoom and ol/interaction.js**

The view extent option now applies to the whole viewport

The view is constrained so only one world is visible

**!!! Removal of deprecated methods : inherits**

**!!! New internal tile coordinates**
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#new-internal-tile-coordinates

Removal of the "vector" render mode for vector tile layers : hybrid

Removal of the "renderMode" option for vector layers
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#removal-of-the-rendermode-option-for-vector-layers

New declutter behavior

New prerender and postrender layer events replace old precompose, render 
and postcompose events

New getVectorContext function provides access to the immediate vector 
rendering API

Layers can only be added to a single map

**!!! The OverviewMap requires a list of layers.**

**!!! The ol/Graticule has been replaced by ol/layer/Graticule**

**!!! ol/format/Feature API change**

**!!! ol/VectorTile API changes**
https://github.com/openlayers/openlayers/blob/main/changelog/v6.0.0.md#olvectortile-api-changes

Drop of support for the experimental WebGL renderer

Removal of the AtlasManager

Change of the behavior of the vector source's clear() and refresh() methods

**!!! Renaming of getGetFeatureInfoUrl to getFeatureInfoUrl**

**!!! getFeaturesAtPixel always returns an array**

Hit detection with unfilled styles


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.1.0.md

A new, performance optimized hit detection API on the layer level, Layer#t 
(pixel) has been introduced. At this point it is implemented for vector, 
vector tile and image vector layers, and is recommended when performance 
is critical, e.g. for hit detection on mouseover.


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.2.0.md

Vector tile layers now have a vector render mode, which brings improved 
zooming experience for sources with not too much data.

Several improvements have been made to the KML parser for reading styles, 
bringing the rendered result much closer to Google Earth.


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.3.0.md

Better support for KML icon colors, as well as fills and outlines in PolyStyle

Several improvements to the Graticule layer, like consistent labeling, 
no more missing graticule lines, and it now works for views that cross 
the date line.

Most of the rendering code can now be run in web workers, e.g. to render 
to an OffscreenCanvas


* https://github.com/openlayers/openlayers/blob/main/changelog/v6.4.0.md

Map interactions work again when ol.css is not included in the build.

Better cache management for tile layers.

**Pull request merged**
